package net.liquidcars.ingestion.infra.input.rest.mapper;

import net.liquidcars.ingestion.domain.model.OfferDto;
import net.liquidcars.ingestion.factory.OfferRequestFactory;
import net.liquidcars.ingestion.infra.input.rest.model.OfferRequest;
import org.junit.jupiter.api.Test;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.boot.test.context.SpringBootTest;
import java.util.List;
import java.util.UUID;

import static org.assertj.core.api.Assertions.assertThat;

@SpringBootTest(classes = {IngestionControllerMapperImpl.class})
public class IngestionControllerMapperTest {

    @Autowired
    private IngestionControllerMapper mapper;

    @Test
    void shouldMapOfferRequestToOfferDtoWithGeneratedId() {
        OfferRequest request = OfferRequestFactory.getOfferRequest();

        OfferDto result = mapper.toOfferDto(request);

        assertThat(result).isNotNull();

        assertThat(result.getId()).isEqualTo(request.getId());
        assertThat(result.getChannelReference()).isEqualTo(request.getChannelReference());
        assertThat(result.getVehicleInstance().getPlate()).isEqualTo(request.getVehicleInstance().getPlate());
        assertThat(result.getPickUpAddress().getAddress().getExtendedAddress()).isEqualTo(request.getPickUpAddress().getAddress().getExtendedAddress());
        assertThat(result.getMail()).isEqualTo(request.getMail());
        assertThat(result.getPrice().getAmount()).isEqualByComparingTo(request.getPrice().getAmount());

        assertThat(result.getId())
                .isNotNull()
                .satisfies(id -> assertThat(id).isNotNull());
    }

    @Test
    void shouldMapListWithDifferentIds() {
        List<OfferRequest> requests = List.of(
                OfferRequestFactory.getOfferRequest(),
                OfferRequestFactory.getOfferRequest()
        );

        List<OfferDto> results = mapper.toOfferDtoList(requests);

        assertThat(results).hasSize(2);

        assertThat(results.get(0).getId())
                .isNotEqualTo(results.get(1).getId())
                .withFailMessage("Each DTO should have a unique UUID generated by the mapper");

        assertThat(results).extracting(OfferDto::getChannelReference)
                .containsExactly(requests.get(0).getChannelReference(), requests.get(1).getChannelReference());
    }

    @Test
    void shouldReturnNullWhenSourceIsNull() {
        OfferDto result = mapper.toOfferDto(null);

        assertThat(result).isNull();
    }
    
}
