package net.liquidcars.ingestion.infra.input.rest.mapper;

import net.liquidcars.ingestion.domain.model.OfferDto;
import net.liquidcars.ingestion.factory.OfferRequestFactory;
import net.liquidcars.ingestion.infra.input.rest.model.OfferRequest;
import net.liquidcars.ingestion.infra.input.rest.model.OfferStatus;
import net.liquidcars.ingestion.infra.input.rest.model.VehicleType;
import org.junit.jupiter.api.Test;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.boot.test.context.SpringBootTest;
import java.util.List;
import java.util.UUID;

import static org.assertj.core.api.Assertions.assertThat;

@SpringBootTest(classes = {IngestionControllerMapperImpl.class})
public class IngestionControllerMapperTest {

    @Autowired
    private IngestionControllerMapper mapper;

    @Test
    void shouldMapOfferRequestToOfferDtoWithGeneratedId() {
        OfferRequest request = OfferRequestFactory.getOfferRequest();

        OfferDto result = mapper.toOfferDto(request);

        assertThat(result).isNotNull();

        assertThat(result.getBrand()).isEqualTo(request.getBrand());
        assertThat(result.getModel()).isEqualTo(request.getModel());
        assertThat(result.getPrice()).isEqualByComparingTo(request.getPrice());

        assertThat(result.getId())
                .isNotNull()
                .satisfies(id -> assertThat(UUID.fromString(id)).isNotNull());
    }

    @Test
    void shouldMapListWithDifferentIds() {
        List<OfferRequest> requests = List.of(
                OfferRequestFactory.getOfferRequest(),
                OfferRequestFactory.getOfferRequest()
        );

        List<OfferDto> results = mapper.toOfferDtoList(requests);

        assertThat(results).hasSize(2);

        assertThat(results.get(0).getId())
                .isNotEqualTo(results.get(1).getId())
                .withFailMessage("Each DTO should have a unique UUID generated by the mapper");

        assertThat(results).extracting(OfferDto::getBrand)
                .containsExactly(requests.get(0).getBrand(), requests.get(1).getBrand());
    }

    @Test
    void shouldReturnNullWhenSourceIsNull() {
        OfferDto result = mapper.toOfferDto(null);

        assertThat(result).isNull();
    }

    @Test
    void shouldMapVehicleType() {
        VehicleType type = VehicleType.CAR;

        OfferDto.VehicleTypeDto result = mapper.mapVehicleType(type);

        assertThat(result).isEqualTo(OfferDto.VehicleTypeDto.CAR);
    }

    @Test
    void shouldMapOfferStatus() {
        OfferStatus status = OfferStatus.ACTIVE;

        OfferDto.OfferStatusDto result = mapper.mapOfferStatus(status);

        assertThat(result).isEqualTo(OfferDto.OfferStatusDto.ACTIVE);
    }

    @Test
    void shouldMapFullRequestWithEnums() {
        OfferRequest request = OfferRequestFactory.getOfferRequest();
        request.setVehicleType(VehicleType.SUV);

        OfferDto result = mapper.toOfferDto(request);

        assertThat(result.getVehicleType()).isEqualTo(OfferDto.VehicleTypeDto.SUV);
        assertThat(result.getStatus()).isNotNull();
    }

    @Test
    void shouldMapOfferStatusToNull() {
        assertThat(mapper.mapOfferStatus(null)).isNull();
    }

    @Test
    void shouldMapVehicleTypeToNull() {
        assertThat(mapper.mapVehicleType(null)).isNull();
    }

    @Test
    void shouldReturnNullWhenListIsNull() {
        assertThat(mapper.toOfferDtoList(null)).isNull();
    }

    @Test
    void shouldMapAllOfferStatusValues() {
        for (OfferStatus status : OfferStatus.values()) {
            OfferDto.OfferStatusDto result = mapper.mapOfferStatus(status);
            assertThat(result.name()).isEqualTo(status.name());
        }
    }

    @Test
    void shouldMapAllVehicleTypeValues() {
        for (VehicleType type : VehicleType.values()) {
            OfferDto.VehicleTypeDto result = mapper.mapVehicleType(type);
            assertThat(result.name()).isEqualTo(type.name());
        }
    }
}
