spring:
  application:
    name: ingestion-api
  threads:
    virtual:
      enabled: true
  servlet:
    multipart:
      max-file-size: -1
      max-request-size: -1
  
  # MongoDB Configuration
  data:
    mongodb:
      uri: ${SPRING_DATA_MONGODB_URI:mongodb://ingestion_service:mongo@mongodb:27017/ingestion_service?authSource=admin}
      database: ingestion_service
  
  # PostgreSQL Configuration
  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/liquidcars?charSet=UTF8}
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
    hikari:
      maximum-pool-size: 10
      minimum-idle: 5
      connection-timeout: 30000
  
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
        jdbc:
          batch_size: 25
        order_inserts: true
        order_updates: true
  
  # Kafka Configuration
  kafka:
    bootstrap-servers: ${KAFKA_BOOTSTRAP_SERVERS:localhost:9092}

    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
      # 'all' ensures the highest durability, waiting for full replication
      acks: all
      retries: 3
      properties:
        # 'linger.ms: 0' forces immediate sending, crucial for our "flush" strategy
        linger.ms: 0
        batch.size: 16384
        delivery.timeout.ms: 120000  # 2 minutes
        request.timeout.ms: 30000     # 30 seconds
        max.block.ms: 6000

    consumer:
      group-id: liquidcars-ingestion-group
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      # 'read_uncommitted' is default (allows reading offers before the report)
      auto-offset-reset: earliest
      enable-auto-commit: false
      properties:
        spring.json.trusted.packages: "*"

      # --- NON-BLOCKING RETRY CONFIGURATION ---
      # This section manages how the consumer behaves when your Service
      # throws the LCIngestionException during the cleanup process.
      retry:
        # How long to wait before the first retry (5 seconds)
        initial-interval: 5000
        # Maximum number of delivery attempts for the same report message
        max-attempts: 5
        # Multiplier for the wait time (1.0 means always wait 2s, 2.0 would double it)
        multiplier: 2.0
        max-interval: 30000  # 30 seconds

    listener:
      # 'record' mode allows each message to be acknowledged individually
      ack-mode: record
      # Ensures the error handler defined in YAML is active
      type: single

    # Spring Batch Configuration
    batch:
      job:
        enabled: false # Don't auto-start jobs on application startup
      jdbc:
        initialize-schema: never
        table-prefix: BATCH_
  
  # Liquibase Migration
  liquibase:
    enabled: false
  # change-log: classpath:db/changelog/postgresql/db.changelog-master.xml
  # File Upload Configuration

  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: ${security.security-profile-issuer}

#Liquibase Mongo config
liquibase:
  mongodb:
    enabled: true
    change-log: classpath:db/changelog/mongodb/db.changelog-master.xml
    url: ${LIQUIBASE_MONGO_URL:mongodb://mongodb:27017/ingestion_service?authSource=admin}
    user: ingestion_service
    password: mongo

# Server Configuration
server:
  port: 8890
  compression:
    enabled: true
  tomcat:
    max-swallow-size: -1

# Server security Configuration
security:
  # Base URL for Keycloak realms
  security-profile-issuer: ${KEYCLOAK_ISSUER:http://keycloak:8080/realms/}
  # CORS Configuration
  allowed-origins-pattern: ${CORS_ALLOWED_ORIGINS:*}
  allowed-methods: GET,POST,PUT,DELETE,OPTIONS,PATCH
  allowed-headers: Authorization,Cache-Control,Content-Type,X-Requested-With
  exposed-headers: Authorization
  allow-credentials: true
  max-age-seconds: 3600
  # List of paths to monitor size
  size-restricted-paths:
    - /batch
    - /url
  max-batch-size: ${SECURITY_MAX_BATCH_SIZE:10MB}
  
# Management & Actuator
management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics,prometheus
  metrics:
    export:
      prometheus:
        enabled: true

# Logging Configuration
logging:
  level:
    root: INFO
    com.orbyn.ingestion: INFO
    org.springframework.batch: INFO
    org.springframework.kafka: DEBUG
    liquibase: INFO
    org.liquibase: INFO
    org.springframework.orm.jpa: DEBUG
    org.springframework.transaction: DEBUG
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} - %msg%n"

# Custom Application Properties
ingestion:
  batch:
    chunk-size: 10
    skip-limit: 2
  kafka:
    topics:
      offers: vehicle-offers
  scheduler:
    enabled: false
    remoteUrl: ${OFFERS_TEST_URL:http://localhost:8083/offers.json}
    cron: "0 */45 * * * *" # Every 45 minutes
    format: json
  purgeScheduler:
    enabled: true
    cron: "0 0 3 * * SUN" # Every Sunday at 3 AM
    days: 7
  syncScheduler:
    enabled: true
    cron: "0 */2 * * * *" # Every 2 minutes
