package net.liquidcars.ingestion.infra.input.rest.model;

import jakarta.validation.ConstraintViolation;
import jakarta.validation.Validation;
import jakarta.validation.Validator;
import jakarta.validation.ValidatorFactory;
import net.liquidcars.ingestion.factory.OfferRequestFactory;
import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.DisplayName;
import org.junit.jupiter.api.Test;

import java.math.BigDecimal;
import java.time.OffsetDateTime;
import java.util.Set;
import java.util.UUID;

import static org.assertj.core.api.Assertions.assertThat;

public class OfferRequestTest {

    private Validator validator;

    @BeforeEach
    void setUp() {
        ValidatorFactory factory = Validation.buildDefaultValidatorFactory();
        validator = factory.getValidator();
    }

    @Test
    @DisplayName("Should test the constructor using Instancio data")
    void testConstructorWithInstancioData() {
        OfferRequest data = OfferRequestFactory.getOfferRequest();

        OfferRequest request = new OfferRequest(
                data.getExternalId(), data.getVehicleType(), data.getBrand(),
                data.getModel(), data.getYear(), data.getPrice(), data.getStatus()
        );

        assertThat(request.getExternalId()).isEqualTo(data.getExternalId());
        assertThat(request.getVehicleType()).isEqualTo(data.getVehicleType());
        assertThat(request.getBrand()).isEqualTo(data.getBrand());
        assertThat(request.getModel()).isEqualTo(data.getModel());
        assertThat(request.getYear()).isEqualTo(data.getYear());
        assertThat(request.getPrice()).isEqualTo(data.getPrice());
        assertThat(request.getStatus()).isEqualTo(data.getStatus());
    }

    @Test
    @DisplayName("Should validate that an object generated by the factory is valid")
    void factoryObjectShouldBeValid() {
        OfferRequest request = OfferRequestFactory.getOfferRequest();

        request.setYear(2024);
        request.setPrice(new BigDecimal("1000.00"));

        Set<ConstraintViolation<OfferRequest>> violations = validator.validate(request);
        assertThat(violations).isEmpty();
    }

    @Test
    @DisplayName("Full coverage of Getters, Setters, and Fluent API")
    void shouldCoverAllAccessors() {
        OfferRequest source = OfferRequestFactory.getOfferRequest();
        OfferRequest target = new OfferRequest();

        target.id(source.getId())
                .externalId(source.getExternalId())
                .vehicleType(source.getVehicleType())
                .brand(source.getBrand())
                .model(source.getModel())
                .year(source.getYear())
                .price(source.getPrice())
                .status(source.getStatus())
                .createdAt(source.getCreatedAt())
                .updatedAt(source.getUpdatedAt())
                .source(source.getSource());

        assertThat(target).isEqualTo(source);
        assertThat(target.hashCode()).isEqualTo(source.hashCode());
        assertThat(target.toString()).contains(source.getExternalId());
    }

    @Test
    @DisplayName("Constraint validation: Minimum year")
    void shouldFailWhenYearIsTooOld() {
        OfferRequest request = OfferRequestFactory.getOfferRequest();
        request.setYear(1899);

        Set<ConstraintViolation<OfferRequest>> violations = validator.validate(request);

        assertThat(violations).anyMatch(v ->
                v.getPropertyPath().toString().equals("year") &&
                        v.getConstraintDescriptor().getAnnotation().annotationType().equals(jakarta.validation.constraints.Min.class)
        );
    }

    @Test
    @DisplayName("Constraint validation: Minimum price")
    void shouldFailWhenPriceIsTooLow() {
        OfferRequest request = OfferRequestFactory.getOfferRequest();
        request.setPrice(new BigDecimal("0.09"));

        Set<ConstraintViolation<OfferRequest>> violations = validator.validate(request);

        assertThat(violations).anyMatch(v ->
                v.getPropertyPath().toString().equals("price") &&
                        v.getConstraintDescriptor().getAnnotation().annotationType().equals(jakarta.validation.constraints.DecimalMin.class)
        );
    }

    @Test
    @DisplayName("Setters Coverage")
    void testStandardSetters() {
        OfferRequest source = OfferRequestFactory.getOfferRequest();
        OfferRequest target = new OfferRequest();

        target.setId(source.getId());
        target.setExternalId(source.getExternalId());
        target.setVehicleType(source.getVehicleType());
        target.setBrand(source.getBrand());
        target.setModel(source.getModel());
        target.setYear(source.getYear());
        target.setPrice(source.getPrice());
        target.setStatus(source.getStatus());
        target.setCreatedAt(source.getCreatedAt());
        target.setUpdatedAt(source.getUpdatedAt());
        target.setSource(source.getSource());

        assertThat(target.getExternalId()).isEqualTo(source.getExternalId());
        assertThat(target.getBrand()).isEqualTo(source.getBrand());
    }

    @Test
    @DisplayName("Full coverage of Equals and toIndentedString")
    @SuppressWarnings("all")
    void testEqualsComplexRamas() {
        OfferRequest req1 = OfferRequestFactory.getOfferRequest();
        OfferRequest req2 = OfferRequestFactory.getOfferRequest();

        assertThat(req1.equals(req1)).isTrue();

        assertThat(req1.equals(null)).isFalse();

        assertThat(req1.equals("any_string")).isFalse();

        req2.setId(UUID.randomUUID());
        assertThat(req1.equals(req2)).isFalse();

        OfferRequest reqNull = new OfferRequest();
        assertThat(reqNull.toString()).isNotNull();
    }
}
