apiVersion: kafka.strimzi.io/v1
kind: KafkaNodePool
metadata:
  name: {{ .Release.Name }}-kafka-pool
  namespace: {{ .Release.Namespace }}
  labels:
    strimzi.io/cluster: {{ .Release.Name }}-kafka
spec:
  replicas: {{ .Values.kafka.replicas }}
  roles:
    - controller
    - broker
  storage:
    type: persistent-claim
    size: {{ .Values.kafka.storage.size }}
    class: {{ .Values.kafka.storage.storageClass }}
