apiVersion: v1
kind: Secret
metadata:
  name: {{ include "charts.fullname" . }}-tls
  namespace: {{ .Release.Namespace }}
type: kubernetes.io/tls
data:
  tls.crt: {{ .Values.tls.servercrt | b64enc }}
  tls.key: {{ .Values.tls.serverkey | b64enc }}
