  APP_CUSTOM_TEST_DATE=NONE
  APP_CUSTOM_TEST_DATE_RUNNING="TRUE"
  ELK_API_KEY=NONE
  ELK_FINGERPRINT=""
  GARRIGUES_CLIENT_ID=0oaa55507xKGBJ4AN417
  GARRIGUES_SECRET=CfgJBtins61wL4NTxwEw4fshOcBYYKOl4tLDobFBDDWjxyk9YlldWA8b6IwBJFwH
  GMAIL_APPLICATION_NAME=LiquidCarsDev
  GMAIL_SERVICE_ACCOUNT_CLIENT_EMAIL=liquidcars-dev@liquidcarsdev.iam.gserviceaccount.com
  GMAIL_SERVICE_ACCOUNT_CLIENT_ID="116921277234540234902"
  GMAIL_SERVICE_ACCOUNT_PRIVATE_KEY="TODO"
  GMAIL_SERVICE_ACCOUNT_PRIVATE_KEY_ID=ecaa668959b6382cd6018dbac0616d7a941c769d
  GMAIL_SERVICE_ACCOUNT_PROJECT=liquidcarsdev
  GMAIL_SERVICE_ACCOUNT_X509_URL=liquidcars-dev%40liquidcarsdev.iam.gserviceaccount.com
  GMAIL_USER_IMPERSONATED=noreply@liquidcars.net
  HTTP_LOG_VERBOSITY=HIGH
  KYC_ALICE_APIKEY=ky8g-D82yvwATKJubn_3-WKJ-i3BjBYh
  KYC_TECALIS_APIKEY=jWa7RAtoEiBAMnYTE8dttzBmdQPnnEerc3sLeJFh
  KYC_TECALIS_PROFILECONFIG=220d49ba-3530-458a-a66f-e12e4339f89d
  MAIL_NOREPLY_ACC=noreply@liquidcars.net
  MAIL_NOREPLY_PWD=apcc ihay hsqo enkf
  OAUTH_ENCRYPTION_PWD=8cf29e98-49a6-4585-9c31-b244fa515fee
  OAUTH_PRIVATE_KEY=acf29e98-49a7-4585-9c32-b244fa515fee
  OAUTH_PRIVATE_KEY_STRONG=MIIEvAIBADANBgkqhkiG9w0BAQEFAASCBKYwggSiAgEAAoIBAQC1ihNBhXUD5+BYqHhooCIkqnnDsSVcdXwleGDnrjXk7kNgs4ufWVucGxA/5yrNvIHituHYmx+LbnPNNRiisUuHHsrdcF/6s9ptafxBk89kEYHzpZm0UDyhiwc7aFR1dYPRtd+0x2h5VHRMXRgFLvV6/ruiPUPqeMeApWbma5B/Sz5lrqW3m3PKm4bajbVwuS7gOs5OBKzAnhl0LSjX2yBS7O24oiEOD0u0pt1SAV8sBuRGyPCUYnECpzp29baquryKSx8MN+XyRG5IXJYsEO5nzBAquCABNEOW9lc6dX2nVsPTaGz2Wq+1EgIMlE7/CWGal6Am4lbBogr+lvwoBfX1AgMBAAECggEAUe/8OPqPki+6ZsnDbxW302zOgLEX999fJVpsAqXy1V1lM+RWBJpEavUcJHumKi4HQdjhnu6FEl3MDrcEY4o6WMZhMgliiLlcwT2xCbg5RyVPzjTUZzo/43nozbuNQ2bDFIhObD4EvZ6Mz1rFWLGVQupurg+Q8+eHxFzjUOUD1y/QCjPEJ7HzAK686j+wRdsFX0keS2hATvTLAjxSNvW+F1kYQwybfCQiZUHCn8hRVv/TAzoj2AMxP10y5hMjcHJJ3Ufs3r/px4HsUnNalcjQ1Jemmxv+MzNi/LvXZJHIJjrhQ45zD1tJ9ydgtj/lOxh3SQeRm0cT16X0FrwUpyxUEQKBgQDk2fyjjdg3xbbhOsg/BDwKQb8H+Yy5aFapxysOGYE4DyGgnAdzoKObg63mUKl3w2RjCfjuicNZOtPvHWbtwis8fDe5XPrbD411wfHIJBzqURY2puisCyq1BdtM4t4RmUmxRZYb+QkZ7Vf7zW6qsfby0YNZN/OFHW+76so26r1MjwKBgQDLE0LUZx9CpJsALRyBR8zFZk/C96uaYiuWHDT9L58iWCgUruRtK4LlHDNMFTknSOoliu9y+zmMJORXZzbXjjFRvWZ/Eit8k3oLbFpIdwwoHSUnRxFjjyOSGMidJ0oLb5zqIjs4iJnj/uVm4tDMMJEUUNOExWKohriYJmNmC+AfOwKBgCoIU5uioNTVjppdlovkdjaYDsMjNZKUNF6ogyLq0k3+kXmTTtcQ6RvWGqmTpRynGZgLK9p8GRIZePWRG+eNYy2PzxhPmI+FksDPJ15QK7Npwz+0dkWrI2PuOHIttQXcdqmFk2V93wsRCbjo6WuWljnQ+2P2n9aSKoSEQjHF+ZDHAoGAFXxmN77pac2ssKoVOAB2w/P9QG2f9GeqoOk/GgKt3Z5iLz4J4RsXcFI5gzVDpMpsK6i1iP7XqeJFXpIHFWtwAGv/qjYr77RS116RdtVRrfTXd35ncpc0dkK1BxufE/KtMYCJr4OUdLEFaIta+B+zWejrWELiG16VrVNydNuQzP0CgYB1IbpuZCBvph0KmfT2Y+OG00vQaBcLAX5nw3mlMSc3G55VGb6pIupYp7I/s8JPI/6scFm5Y90gLR9RoQq/I6vnYYMxwG0zKXJgBUYC7ZjM6RtHP6zfVxQ56gP1oRJE1NB+qeY7mYT91PV/InkJ1+yYp618L9iUVSGktafN0vNnkQ==
  OAUTH_PUBLIC_KEY_STRONG=MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAtYoTQYV1A+fgWKh4aKAiJKp5w7ElXHV8JXhg56415O5DYLOLn1lbnBsQP+cqzbyB4rbh2Jsfi25zzTUYorFLhx7K3XBf+rPabWn8QZPPZBGB86WZtFA8oYsHO2hUdXWD0bXftMdoeVR0TF0YBS71ev67oj1D6njHgKVm5muQf0s+Za6lt5tzypuG2o21cLku4DrOTgSswJ4ZdC0o19sgUuztuKIhDg9LtKbdUgFfLAbkRsjwlGJxAqc6dvW2qrq8iksfDDfl8kRuSFyWLBDuZ8wQKrggATRDlvZXOnV9p1bD02hs9lqvtRICDJRO/wlhmpegJuJWwaIK/pb8KAX19QIDAQAB
  OAUTH_ZERO_COM_CLIENT_ID=Mn8sGyxyAvTyHTCi3Dkf51z5vCD9NlXI
  OAUTH_ZERO_COM_CLIENT_ID_ADMINWEB=72cLnBmbyWrSqHiwrPPqXBptXxgp6UiO
  OAUTH_ZERO_COM_CLIENT_ID_PROWEB=ktvOmvRpwcmDxTyBhVZrnMioBlMlbz3s
  OAUTH_ZERO_COM_CLIENT_SECRET=l1OhH5LZWEryU2vYe_jfCQQvsTpq9wIqvDRJnXGcWUppuCkb57KrSRLu7a68RAq_
  OAUTH_ZERO_COM_CLIENT_SECRET_ADMINWEB=Vn0GW0iBihpFPhnIrwiNa9q6_bdfLJ_pP0UfFEji9bG8smRibHr2EnlWeAI1UYA4
  OAUTH_ZERO_COM_CLIENT_SECRET_PROWEB=62qN8doBYpETEtABOttJl_DvjII6cfeFFzGRIc9TPZvDrNhOq-gmW_Q0P9gVe1Qm
  OAUTH_ZERO_COM_HASH=a9db0742db0d1e9243f5e78a4f189791cbbf2b170494627c25009eeeefa3abc6
  SERVER_SSL_KEY_STORE_PASSWORD=LCCars01
  SPRING_DATASOURCE_PASSWORD=a147b060-Fe68-446B-a27b-db4c0079fca9
  SPRING_DATASOURCE_URL=jdbc:postgresql://db-lc-dev-eu.postgres.database.azure.com:5432/liquidcars?sslmode=require
  SPRING_DATASOURCE_USERNAME=postgreslc
  SPRING_RABBITMQ_PASSWORD=5c651eb8-7529-418a-b744-1ea623d78274
  SPRING_RABBITMQ_USERNAME=lcrabbit
  SPRING_RABBITMQ_HOST=rabbitmq.messaging.svc.cluster.local
  SPRING_RABBITMQ_PORT=5672
  SPRING_RABBITMQ_VIRTUAL_HOST=/liquidcars-dev
  SPRING_REDIS_PASSWORD=""
  STRIPE_APIKEY=sk_test_51N41KwBSqTqI3ZGkqcBvotYVIiJp72HfkY1KmAqwpWLMHB4GjoNy9RlDdaUDHOIpkTQxTCC9psS2wf5PIjOWo1Ze00X1GasZGi
  STRIPE_WEBHOOK_CONNECTED_ACCOUNTS_SECRET=whsec_mtBI3IFlhACm0UBUYtmGeJ7M6LRLlQk7
  STRIPE_WEBHOOK_SECRET=whsec_b3at8aRAHyHxmXQuGg0CUDlcGWcIr5GT
  SWIPOO_CLIENT_ID=LMejRHbcIiMtCdaMp0Lir2kned21SsLw
  SWIPOO_CLIENT_SECRET=ghb0t_DZRmLzgbn1nT7poEQS9-uOI2gvrXuxs3GDpXR-6zUW2SAutkzjxWqC9rFV
  SWIPOO_INTERMEDIARY_ID=8b0347ec-9e17-4949-8b4f-6db2a18ed2d1
  SPRING_PROFILES_ACTIVE="DEV"
  DUMMY_DEV_ENV_MODE="Y"