image:
  repository: liquidcars.azurecr.io/liquidcars/test/ingestion

configData:
  SPRING_RABBITMQ_VIRTUAL_HOST: /liquidcars-test
  SPRING_DATASOURCE_URL: jdbc:postgresql://db-lc-dev-eu.postgres.database.azure.com:5432/liquidcars-test?sslmode=require&charSet=UTF8
  SPRING_DATASOURCE_USERNAME: postgreslc
  SPRING_DATASOURCE_PASSWORD: a147b060-Fe68-446B-a27b-db4c0079fca9
  SPRING_PROFILES_ACTIVE: "TEST"
  SPRING_RABBITMQ_HOST: shared-rmq.rabbitmq-system.svc.cluster.local
# kg secret -n rabbitmq-system user-liquidcar-test-user-credentials -o yaml
#  user-liquidcar-test
  SPRING_RABBITMQ_USERNAME: TkhVaVRRT1hGbllzMkZSQkhGZVplUW5qa1hMRDZmYUY=
  SPRING_RABBITMQ_PASSWORD: Mk9ZMUV1aGRqenMyY1hqdThBaUhTbkUyWUVpN2puUEw=
  SPRING_RABBITMQ_VIRTUAL_HOST: /liquidcars-test
